# Generated by Django 4.2.7 on 2023-11-13 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCardAccount",
            fields=[
                (
                    "account_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="finance.account",
                    ),
                ),
                ("credit_limit", models.DecimalField(decimal_places=2, max_digits=12)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            bases=("finance.account",),
        ),
        migrations.CreateModel(
            name="SavingsAccount",
            fields=[
                (
                    "account_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="finance.account",
                    ),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            bases=("finance.account",),
        ),
        migrations.RenameField(
            model_name="account",
            old_name="owner",
            new_name="user",
        ),
        migrations.AddField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("savings", "Savings"),
                    ("credit_card", "Credit Card"),
                    ("checking", "Checking"),
                ],
                default="checking",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(default="Checking", max_length=50),
        ),
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="finance.account",
            ),
        ),
    ]
